# Generated by Django 4.1 on 2022-08-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
